import type { Metadata } from 'next';
import { ThemeProvider } from '@/components/theme-provider';
import { Poppins, Lora } from 'next/font/google';
import './globals.css';
import Footer from '@/components/layouts/footer';
import Sidebar from '@/components/sidebar';

const poppins = Poppins({
	variable: '--font-poppins',
	subsets: ['latin'],
	weight: ['400', '500', '600', '700'],
});

const lora = Lora({
	variable: '--font-lora',
	subsets: ['latin'],
	weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='fr'
			suppressHydrationWarning>
			<body className={`${poppins.variable} ${lora.variable} antialiased`}>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange>
					<div className='flex min-h-screen'>
						<Sidebar />
						<div className='flex-1 flex flex-col justify-between'>
							{children}
							<Footer />
						</div>
					</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
